# port
server:
  port: 8081

#datasource
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##TOYPROJECT
    password: TOYPROJECT
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  freemarker:
    cache: false
  mail:
    host: smtp.naver.com
    port: 465
    username: minsukim0743
    password: YHBU7L5U81N5
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.toyproject.springsecurity.login.model.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info